### ISSUE TITLE
Hard dependency with ngi_pipeline

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#104]
@b97pla do you think we could make the dependency with `ngi_pipeline` not so hard? For example, on the NASs it is not needed at all, and when installing TACA not only is installing `ngi_pipeline`, but also requiring to modify our `.bash_profile` files to add the Charon environment variables:

> ValueError: Could not get required environmental variable "'CHARON_API_TOKEN'"; cannot connect to database.

do you think a 

```python
try:
    import ngi_pipeline
except ImportError:
    logger.warn('No ngi_pipeline installation found, functionalities dependent on the pipeline will not work')
```

would work well enought? Or that this is a good idea at all?

**Comment by guillermo-carrasco** [comment]
ping @b97pla , what do you think about this? :)

**Comment by b97pla** [comment]
sorry, I didn't get these updates.. yes absolutely, this makes sense

**Comment by b97pla** [comment]
how would you expect the tests to behave in case this dependency is missing, should they fail or be ignored?

**Comment by guillermo-carrasco** [comment]
I think they should be ignored if the dependency is missing, _or_ for the automated tests, just explicitly install the `ngi_pipeline`, _or_ implement a plugin `taca-ngi-pipeline` which `taca` is independent with, that runs its tests.. hmm I would really like to implement this plugin thing, but I (we, if you agree) have to think how. 

@robinandeer 's [chanjo](https://github.com/robinandeer/chanjo)/[chanjo-report](https://github.com/robinandeer/chanjo-report) code should be a good start!

**Comment by b97pla** [comment]
I started working on a [plugin](https://github.com/b97pla/taca-ngi-pipeline), let's see if it will be fruitful

**Comment by b97pla** [comment]
i believe this issue can be closed now
