### ISSUE TITLE
Dependency not working!! 

### ISSUE THREAD

**Issue by senthil10** [SciLifeLab/TACA#142]
Package is not automatically installing the "dependency" packages (specified in `dependency_links.txt`) anymore :angry:

**Comment by Galithil** [comment]
The setup.py seems okay, did you run the install from the main dir ?

**Comment by senthil10** [comment]
Yes, I ran `python setup.py install` from the main directory

And this is message I got while installing regarding `flowcell_parser`

```
Searching for flowcell-parser==1.0
Best match: flowcell-parser 1.0
Processing flowcell_parser-1.0-py2.7.egg
flowcell-parser 1.0 is already the active version in easy-install.pth
Installing get_flowcell_stats.py script to /home/hiseq.bioinfo/.miniconda/envs/master/bin
Installing upload_flowcell_to_statusdb.py script to /home/hiseq.bioinfo/.miniconda/envs/master/bin

Using /home/hiseq.bioinfo/.miniconda/envs/master/lib/python2.7/site-packages/flowcell_parser-1.0-py2.7.egg
```
But while running, it complains couldn't find `import` (not saying `package` missing). So I guess it is not installing fully (?) :eyes:  

Anyhow, manual installation fixed the problem :+1: but not a neat solution.
