### ISSUE TITLE
Bash Completion!!

### ISSUE THREAD

**Issue by senthil10** [SciLifeLab/TACA#174]
Not really an *issue*, Just to letting you guys know. That `TACA` (*click* based applications) commands can be [auto-completed](http://click.pocoo.org/5/bashcomplete/). 

Thought might be useful for any other (*"lazy"*) guy like me out there :joy:

**Comment by ewels** [comment]
![blew my mind](http://s2.quickmeme.com/img/dc/dc64b9f2d07d20ba1f6d3d3287d25577a1ffe9332c1ea32196d1a326d55b228d.jpg)
