### ISSUE TITLE
Samplesheets for HAS 

### ISSUE THREAD

**Issue by Galithil** [SciLifeLab/TACA#37]
That might not be true for the latest versions, but if you want to make the samplesheets HAS compatible, you need a key named "Workflow" under the [Header] key, and possibly a [Settings] key before [Data]

**Comment by guillermo-carrasco** [comment]
HAS?

**Comment by Galithil** [comment]
Hiseq Analysis software, Illumina's pipeline.

**Comment by guillermo-carrasco** [comment]
oh! thanks @Galithil ... hmm but are we considering that? I' confused.

**Comment by Galithil** [comment]
I don't know, I was asked to open an issue with the steps on how to make a
samplesheet for the HAS.

**Comment by vezzi** [comment]
Nothing to be prioritised but in case we decide to use HAS we need to be able to fix the sampleSheet accordingly

**Comment by alneberg** [comment]
Closing this since it was probably not decided to be used.
