### ISSUE TITLE
archive funcitonality not looking at the days

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#68]
Even though it is in the argument list

```
def archive_to_swestore(days, run=None)
```

It is not used in this method (it is in cleanup), so basically it will archive *all* the runs, regardless whatever you specify as old.

**Comment by senthil10** [comment]
@guillermo-carrasco : I think it was because of the `option type` in click. I has the same issue, but changing to this

```@click.option('-d', '--days', type=click.INT, default=None, help="Days to consider as thershold")```

seemed to work, `type=click.INT`

**Comment by senthil10** [comment]
Probably I will make a PR before today evening with couple of changes, you can review it and let me know of the changes you dint like :sweat_smile:

**Comment by guillermo-carrasco** [comment]
no no, the issue is simpler: I am *not using it in the code* :sweat_smile: so it is my fault.

The click option as it is now works okay for cleanup. As @robinandeer said, if you specify a `default=2` (or whatever integer), click assumes that the value for that option is an integer.

:-)

**Comment by senthil10** [comment]
haha.. makes sense. I changed the `default` to `None` probably thats why it dint work for me :stuck_out_tongue:

**Comment by robinandeer** [comment]
Yeah, ``None`` is the default if you don't set a default I would assume, hehe
