### ISSUE TITLE
Remove contributors from README

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#79]
What do you think? It is implicit in the commit history. Actually, it is availably in the "Contributors" tab on the repository so... one less thing to keep up to date.

**Comment by ewels** [comment]
:+1:

**Comment by guillermo-carrasco** [comment]
![screen shot 2015-03-19 at 11 59 04](https://cloud.githubusercontent.com/assets/1574147/6729109/703dfca8-ce2f-11e4-8eda-393360a04a09.png)

**Comment by senthil10** [comment]
hahaha.. look at your plot @guillermo-carrasco it so orange :stuck_out_tongue_winking_eye:

**Comment by guillermo-carrasco** [comment]
:flushed: well that's just because I started the project, it will balance eventually :-)

**Comment by Galithil** [comment]
I kinda disagree, these graphs are not very good, I think. If you look at the graph for genomic status, I am not even listed as a contributor. Somethow, Phil has ownership of most of my commits ...

**Comment by guillermo-carrasco** [comment]
Hmm... does any of [these](https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/) comply? Maybe the last one?

**Comment by mariogiov** [comment]
Nice work Phil! Screwing the French yet again! Ha ha!

**Comment by ewels** [comment]
Hah, @Galithil edited his post - I don't have ownership, his commits were just tied to an incorrect e-mail address so no-one had ownership..

**Comment by guillermo-carrasco** [comment]
wait I missed everything, what happeneed?

**Comment by Galithil** [comment]
I wrongly accused Phil to steal my commits through witchcraft, while actually, most of my commits are not credited to me because they are credited to an email address that does not exist (denismoreno@130-229-8-17-dhcp.wlan.ki.se)
I then edited my post. That's pretty much it.
