### ISSUE TITLE
Write some meaningful tests!

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#85]
Yes, we should. This is getting complicated, and everytime we change something (i.e now that I am actually changing the structure of the analysis part, see this), we risk to break things. For now there is only one single test for the analysis part, we should:
- [ ] Improve the analysis test and adapt it to the new structure
- [ ] Write tests for storage cleanup
- [ ] Write tests for storage archive

We need to:
1. Create a directory structure that resembles what we have on the servers, to run **automated tests**.
2. Have a minimalistic dataset (like _very_ minimalistic), to run tests on
3. Fake commands that we cannot execute in Travis-CI (bcl2fastq, archive to swestore, etc), two options:
   - Create fake binaries that mimic the commands :-1: 
   - Use [Python Mocking library](http://www.toptal.com/python/an-introduction-to-mocking-in-python) :+1: 

Issue to be extended with more details soon.

**Comment by robinandeer** [comment]
You might want to consider adding to your ``CONTRIBUTING.md`` that adding tests is a requirement before a PR is merged. I get this is what some open source projects require at least: https://github.com/audreyr/cookiecutter/blob/master/CONTRIBUTING.rst

**Comment by guillermo-carrasco** [comment]
we've never done it (tracking test coverage), but adding that to `CONTRIBUTING.md` sounds like a good idea, even if that would force even the main developers (ehem ehem..) to write tests :stuck_out_tongue:

**Comment by senthil10** [comment]
:joy: :joy: 
![image](https://cloud.githubusercontent.com/assets/5311007/7117746/1bfd17de-e1fb-11e4-9230-2974fba97b89.png)

**Comment by ssjunnebo** [comment]
Closing this since coverage is now [at 87.49%](https://codecov.io/gh/SciLifeLab/TACA).

**Comment by ewels** [comment]
![wow](https://media.tenor.com/images/559bcafc9efa1c282d7a2773bc88412b/tenor.gif)

**Comment by ewels** [comment]
This is huge @ssjunnebo - amazing work! You managed to do something that @guillermo-carrasco, @robinandeer, @senthil10 and I never achieved in our time at the NGI 😆 

![amazing](https://i.imgur.com/VIMxiWo.gif)
