### ISSUE TITLE
Config management

### ISSUE THREAD

**Issue by robinandeer** [SciLifeLab/TACA#87]
Since this is one of the potential cross over points between Clinical and NGI I would like to extend a request to get some feedback on how we have been thinking around handling this question: Clinical-Genomics/cghq#4

For usage example check the lonesome (so far) test and the fixture config example.

What do you think?
- Is it a good or bad idea to go for a more complex subclassing of ``dict``?
- How would you best structure the config file; flat or grouped?
- What data should go into the config? Is there anything as "too sensitive" data?

**Comment by guillermo-carrasco** [comment]
Hi @robinandeer !

> Is it a good or bad idea to go for a more complex subclassing of dict?

Hmm I don't really understand what are you doing with that config class. How is it better/more helpful than a simple YAML parser? That's what we have been doing till now and works really well for us. It is true though that we have pretty unstructured config files. So...

> How would you best structure the config file; flat or grouped?

We have a different config file for each of our repos. I'm happy with that, but I'm not as happy with the structure of these files, which basically is... non-existent. We keep adding sections and subsections as needed, and sometimes it makes it difficult to know where to put what. 

Also, we generally don't check the config files when starting the program (whichever), so you'll get a runtime error if some section is missing. I only do some [basic checking](https://github.com/SciLifeLab/TACA/blob/master/taca/analysis/analysis.py#L18) for the demultiplexing part in TACA. 

> What data should go into the config? Is there anything as "too sensitive" data?

These config files are generally not placed in GitHub, other than examples. So we use to put everything (usernames and passwords) in there, which are only accessible by us... hopefully.

**Comment by robinandeer** [comment]
Tack för dina insikter!

I've been playing with the idea that we could keep a unified config file that orders key/value pairs based on context (mysql, LIMS, etc.) rather than project. I have no idea if this is manageable but I'd kind of like to try :smirk:

The point would be to focus on generalized external packages that don't need to worry about the practicalities of logging, reading configs etc. A central project TACA/CGHQ would route functions calls from external packages and be responsible for feeding in relevant config values and decide how and where to log stuff.

> How is it [a config class] better/more helpful than a simple YAML parser?

I like keeping things simple but I want to exhaust our possibilities. It could provide a nice way of building an interface/API. You could build in validation for example or what about this:

```python
>>> config.mysql.username
mysql_username
>>> config.mysql.url  # this is a dynamic property ^^
dialect+driver://mysql_username:password@host:port/database
```

So you can build in processing of raw config values and keep the contents of the config DRY!

I'm also a little on the fence about [passing in a whole config dict as a parameter to a function](https://github.com/SciLifeLab/TACA/blob/master/taca/analysis/analysis.py#L164) :stuck_out_tongue_winking_eye: --- so now I'm curious what the benefit of this is? ^^

**Comment by pekrau** [comment]
My opinions:

A unified config file is not a good idea. It will become huge and eventually unstructured. If you begin to structure it so that one section belongs to one system/program, then why keep it in a single file in the first place? If you have some config that is common to many systems, then keep it separate, and load it as such wherever it is needed.

Simple YAML parser, or special interface: Why complicate things? Use the interface known as 'dict', and don't complicate it more than that. I am more and more of the opinion that we are too keen on layers, such as ORMs. Very rarely does one actually gain anything by these layers, they do not give the decoupling  often seen as the goal. And a layer is yet another component to maintain. So a simple YAML parser is a good enough interface.

**Comment by robinandeer** [comment]
Thank you @pekrau!

I trust your experience. I may have gotten a little ahead of myself. I agree that if a ``dict`` works there's no reason to complicate things. I will try to solve our problem in the most straight forward manner!

As a compromise for allowing multiple config files I would feel better if they were still namespaced them under e.g. ``~/.clinical/<program>.yaml``. I will start there I think. It will make it cleaner and easier to introduce other team members to our practices.

**Comment by pekrau** [comment]
From the Zen of Python: http://zen-of-python.info/namespaces-are-one-honking-great-idea--lets-do-more-of-those.html

So your idea is probably good.

**Comment by robinandeer** [comment]
Thanks for the hints :smiley:
