### ISSUE TITLE
Option to compress a run

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#92]
without archiving it?

EDIT: Can we also add option to handle multiple runs via `-r` option ?

**Comment by senthil10** [comment]
@guillermo-carrasco : I like it, it should be an easy thing to add I guess :) I also added an 'EDIT' to your question, which is what we discussed earlier. what do you think ?

**Comment by guillermo-carrasco** [comment]
I think its doable and useful :-), tack!
