### ISSUE TITLE
Stat file created and kept even if the run is not archived

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#93]
there are some runs in `nosync` that don't have an `RTAComplete.txt` file, so they probably were moved manually. When TACA tries to archive them, it generates the stat file but at the end does not remove it, which would be the expected behaviour.

```
(master)hiseq.bioinfo@nas-8:/srv/illumina/hiseq_data/nosync$ ls
150123_ST-E00198_0041_AH22N2ALXX  150223_ST-E00198_0042_AH2VK2CCXX  archived  archive.sh  ssverify.key

(master)hiseq.bioinfo@nas-8:/srv/illumina/hiseq_data/nosync$ taca storage --days 10 archive --backend swestore --max-runs 4 

2015-04-22 11:54:08,815 - TACA - INFO - Archiving old runs to SWESTORE
2015-04-22 11:54:08,815 - TACA - INFO - Checking /srv/illumina/hiseq_data/nosync directory
2015-04-22 11:54:08,930 - TACA - INFO - Checking /srv/illumina/miseq_data/nosync directory
2015-04-22 11:54:08,931 - TACA - INFO - No old runs to be archived

(master)hiseq.bioinfo@nas-8:/srv/illumina/hiseq_data/nosync$ ls
150123_ST-E00198_0041_AH22N2ALXX            150223_ST-E00198_0042_AH2VK2CCXX            archived    ssverify.key
150123_ST-E00198_0041_AH22N2ALXX.archiving  150223_ST-E00198_0042_AH2VK2CCXX.archiving  archive.sh
```

**Comment by senthil10** [comment]
@guillermo-carrasco : I think its cause we run it parallel via `pool`, it is not throwing any error when it fails [here](https://github.com/SciLifeLab/TACA/blob/master/taca/storage/storage.py#L234) with `OSError` when `RTAComplete.txt` file missing.

P.S: You may already aware of it and "working" on a "work around" ;)

**Comment by guillermo-carrasco** [comment]
well spotted @senthil10 :wink: no I didn't look at it yet, but thanks for pointing, that's an easy fix!
