### ISSUE TITLE
Use charon api-wrappers from charon repo 

### ISSUE THREAD

**Issue by b97pla** [SciLifeLab/TACA#98]
There is a dependency on ngi_pipeline in the deliver module. This should be refactored out (or the ngi_pipeline repo refactored to isolate the charon api wrappers).

**Comment by guillermo-carrasco** [comment]
+1

**Comment by mariogiov** [comment]
I would suggest we move the CharonSession python object to Charon.

**Comment by mariogiov** [comment]
Which I suppose I could do.

**Comment by b97pla** [comment]
that'd be great Mario!

**Comment by Galithil** [comment]
I would advise against doing that. It would mean that you would have to deploy Charon (a tornado app with its own dependencies) just to access the wrapper classes. Can't we have a separate repo for that ?

**Comment by guillermo-carrasco** [comment]
:+1: @Galithil

**Comment by b97pla** [comment]
I take the liberty of closing this issue as it doesn't have much to do with TACA anymore...

**Comment by mariogiov** [comment]
Good point @Galithil
