### ISSUE TITLE
Check for existing checksum files

### ISSUE THREAD

**Issue by b97pla** [SciLifeLab/TACA#99]
When staging a delivery, the script should check for an existing checksum file for each file to make it possible to calculate this outside of TACA. 

In addition, this should make it possible to resume a delivery that was only staged.

**Comment by guillermo-carrasco** [comment]
@b97pla isn't this already implemented [here](https://github.com/SciLifeLab/TACA/blob/master/taca/utils/transfer.py#L105)?

**Comment by b97pla** [comment]
@guillermo-carrasco not entirely, since the delivery script is explicitly calculating checksums. [This PR](https://github.com/SciLifeLab/taca-ngi-pipeline/pull/9) implemented using files for caching as described in this issue tho.

**Comment by guillermo-carrasco** [comment]
awesome!
